project:
  type: book

book:
  title: "FS4R"
  author: "Job Spijker e.a."
  date: "1/7/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - yourenotalone.qmd
    - reproducible.qmd
    - documentation.qmd
    - versioncontrol.qmd
    - goodcoding.qmd
    - testing.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto



